### PR TITLE
Use more appropriate SYSTEMDRIVE for WinRM connections without a user

### PR DESCRIPTION
**Pull request by tyler-ball**
Thank you https://github.com/iserje and https://github.com/Tensibai for the issues and suggested fixes! I lack Windows knowledge so thank you for helping me out here.

## Description
Fixes https://github.com/chef/license-acceptance/issues/50
Fixes https://github.com/chef/license-acceptance/issues/45

## Related Issue
N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by iserje** [comment]
@tyler-ball Has the change been committed? I'm still experiencing the same issues. Or may be a new release would have to be created?

**Comment by tas50** [comment]
@iserje This change shipped in Chef 15.0.298, which went out last night. Let us know if you're having issues with that release.

**Comment by mgreenegit** [comment]
@tyler-ball this same issue appears with InSpec.  What can I do to help?

**Comment by tyler-ball** [comment]
@mgreenegit Open an issue in https://github.com/inspec/inspec linking to this issue. The suggested solution should be to update the `license-acceptance` gem pin to `>= 1.0.11`

**Pull request merged**
